### ISSUE TITLE
继续lock，喷完我就lock，对吧

### ISSUE THREAD

**Issue by bradfordzhang** [ChinaMeng300/C--Code-Repository-C--Application-Download#4]
就是看不惯你学点皮毛就在那里装B，谁给你的权力随便骂别人垃圾？

**Comment by ChinaMeng300** [comment]
我骂谁垃圾了？我锁定不锁定是我的权利吧？

**Comment by bradfordzhang** [comment]
抖音下面，自己骂过自己都不知道吧，我有说lock不是你的权利吗

**Comment by ChinaMeng300** [comment]
Edge 本来就垃圾？抄Chrome？整个动画都一模一样？最后扩展都通用？
Windows 我没说垃圾，况且那个作品我删了？

**Comment by bradfordzhang** [comment]
我说的是你骂你抖音作品下面评论的人垃圾，人家质疑你你就垃圾垃圾的，又说估计人家啥也不会

**Comment by ChinaMeng300** [comment]
评论的80%都是来喷我的？抖音说允许别人随便骂人？我还不能回击了？还有我不止会控制台程序，我可以搞PyGame？懂？

**Comment by bradfordzhang** [comment]
pygame很NB？人家质疑你你就垃圾垃圾的？你不会解释？你那几个作品都什么意思？蔑视大部分抖音用户？把自己搞得很高大上？

**Comment by ChinaMeng300** [comment]
我不会解释？我啥时候说lj这两个字了？我只是说“lj”？还有很多人说我不会录屏？那我不喷他们喷你啊？

**Comment by bradfordzhang** [comment]
懂了，lj不等于垃圾，你就是个lj，可以吗

**Comment by ChinaMeng300** [comment]
我本来就是lj？我还没成年？我本来就是xxs？明明自己没做错事就有人质疑？我为什么不能反击呢？还有就是我来就是lj，对于你们这些大佬惹不起`#我很NB`行了吧？

**Comment by bradfordzhang** [comment]
未成年很牛？人家质疑你一下，你回答不行吗，非要硬性，而且你看你的作品的整体画风，不是在炫耀就是在夸张，你评论的15W代码在哪呢？

**Comment by ChinaMeng300** [comment]
我有说源文件15w行？我是说打包后的二进制？？

**Comment by bradfordzhang** [comment]
你自己去看吧，你说的源码15W

**Comment by bradfordzhang** [comment]
你家看二进制行数？

**Comment by ChinaMeng300** [comment]
我家看啊，怎么了？

**Comment by ChinaMeng300** [comment]
不是吧不是吧，自己的看法都要管？你怎么不管我大脑呢？

**Comment by ChinaMeng300** [comment]
删储存库行吧？

**Comment by bradfordzhang** [comment]
那我去面试，说我代码行数100W，源代码就1000行，人家会面试我吗

**Comment by ChinaMeng300** [comment]
删储存库可不可以解决？

**Comment by ChinaMeng300** [comment]
我玩不起了，行了吧

**Comment by bradfordzhang** [comment]
不要你删，要你低调，我认识个人，刚学贼NB，现在被人家后学的超了，NOIP人家省一，他省二

**Comment by ChinaMeng300** [comment]
我是傻B，我是装13鬼

**Comment by bradfordzhang** [comment]
你删库有用吗？

**Comment by bradfordzhang** [comment]
请你，以后视频低调一点，行吗

**Comment by ChinaMeng300** [comment]
注销Git总行了？
、
注销抖音号？注销Youtube 频道？

**Comment by ChinaMeng300** [comment]
低调性啊

**Comment by bradfordzhang** [comment]
你现在的行为难道和那些营销号用cmd搞得自己很NB不一样？

**Comment by bradfordzhang** [comment]
你看奥，都消消气，我给你捋清楚

**Comment by bradfordzhang** [comment]
可以吗，都消消气

**Comment by bradfordzhang** [comment]
![images.jpg](https://i.loli.net/2020/08/12/mtFhzr5HlIuq2bM.jpg)

**Comment by bradfordzhang** [comment]
《二 十 五 万 行 的 代 码》

**Comment by bradfordzhang** [comment]
别提二进制了，你手写二进制？
